name: Debug Docker Build

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Debug secrets
        run: |
          echo "Checking secrets..."
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "❌ DOCKERHUB_USERNAME is empty or not set!"
          else
            echo "✅ DOCKERHUB_USERNAME is set"
            echo "Username length: ${#DOCKERHUB_USERNAME}"
          fi
          
          if [ -z "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" ]; then
            echo "❌ DOCKERHUB_ACCESS_TOKEN is empty or not set!"
          else
            echo "✅ DOCKERHUB_ACCESS_TOKEN is set"
          fi
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          
      - name: Test tag generation
        run: |
          echo "Generated tags would be:"
          echo "${{ secrets.DOCKERHUB_USERNAME }}/devops-day3:latest"
          echo "${{ secrets.DOCKERHUB_USERNAME }}/devops-day3:${{ github.sha }}"
